-- Sample data for Review Ideas feature
-- Note: Run this manually or set spring.sql.init.mode=always temporarily

INSERT INTO ideas (title, category, description, status, primary_actor, owner_name, created_at, updated_at) VALUES
('Mobile App Redesign', 'Product Enhancement', 'Redesign the mobile app interface to improve user experience and increase engagement rates. Focus on modern UI patterns, smooth animations, and intuitive navigation.', 'APPROVED', 'Sarah Chen', 'Sarah Chen', '2025-11-01 10:30:00', '2025-11-07 14:20:00'),
('AI Content Generator', 'Innovation Project', 'Develop an AI-powered content generation tool for marketing copy and social media posts. Integrate with GPT models and provide customizable templates for different content types.', 'UNDER_REVIEW', 'Alex Johnson', 'Alex Johnson', '2025-11-02 09:15:00', '2025-11-06 16:45:00'),
('Sustainable Packaging', 'Environmental Initiative', 'Implement eco-friendly packaging solutions to reduce environmental impact. Research biodegradable materials and partner with sustainable suppliers.', 'APPROVED', 'David Kim', 'David Kim', '2025-11-01 14:00:00', '2025-11-05 11:30:00'),
('Analytics Dashboard', 'Data Visualization', 'Create an advanced analytics dashboard that provides real-time insights into user behavior, engagement metrics, and conversion funnels. Include customizable widgets and export capabilities.', 'NEW', 'Rachel Green', 'Rachel Green', '2025-11-03 11:20:00', '2025-11-08 09:10:00'),
('Security Enhancement', 'Infrastructure', 'Implement advanced security measures including two-factor authentication and encryption for sensitive data. Conduct security audit and penetration testing.', 'REJECTED', 'James Miller', 'James Miller', '2025-10-28 08:45:00', '2025-11-04 13:15:00'),
('Voice Assistant Integration', 'User Experience', 'Integrate voice assistant capabilities to allow users to interact with the application using natural language commands. Support for multiple languages and custom voice commands.', 'APPROVED', 'Sophie Turner', 'Sophie Turner', '2025-10-30 13:30:00', '2025-11-03 10:00:00'),
('Customer Loyalty Program', 'Marketing Strategy', 'Develop a comprehensive loyalty program with rewards, tiers, and exclusive benefits for repeat customers. Gamification elements to increase engagement.', 'UNDER_REVIEW', 'Mark Johnson', 'Mark Johnson', '2025-11-04 15:00:00', '2025-11-07 17:30:00'),
('API Documentation Portal', 'Developer Tools', 'Create a comprehensive API documentation portal with interactive examples, code samples in multiple languages, and a sandbox environment for testing endpoints.', 'NEW', 'Jessica Adams', 'Jessica Adams', '2025-11-05 10:45:00', '2025-11-08 08:00:00');
